name = "Orion Lab Research Group"
license = "MIT"
licenselink = "https://github.com/wowchemy/starter-hugo-research-group/blob/main/LICENSE.md"
description = "In Orion Lab we do Artificial Intelligence for Earth Observation"
homepage = "https://orion-ai-lab.github.io"
demosite = "https://orion-ai-lab.github.io"
tags = ["academic",
        "university",
        "research",
        "publications",
        "widgets",
        "portfolio",
        "responsive",
        "clean",
        "company",
        "blog",
        "events",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "landing page",
        "contact form",
        "mobile",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "slide"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "Ioannis Prapas"
  homepage = "https://iprapas.github.io"
